# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # SWARM VMs
  config.vm.define "swarmA" do |swarmA|
    swarmA.vm.box = "centos/7"
    swarmA.vm.network "private_network", ip: "192.168.33.10"
    swarmA.vm.provider "virtualbox" do |vba|
      # Display the VirtualBox GUI when booting the machine
      vba.gui = true
      # Customize the amount of memory on the VM:
      vba.memory = "1024"
    end
    swarmA.vm.provision "shell", inline: <<-SHELL
      yum -y update
      yum -y install epel docker
    SHELL
  end
  config.vm.define "swarmB" do |swarmB|
    swarmB.vm.box = "centos/7"
    swarmB.vm.network "private_network", ip: "192.168.33.11"
    swarmB.vm.provider "virtualbox" do |vbb|
      # Display the VirtualBox GUI when booting the machine
      vbb.gui = true
      # Customize the amount of memory on the VM:
      vbb.memory = "1024"
    end
    swarmB.vm.provision "shell", inline: <<-SHELL
      yum -y update
      yum -y install epel docker
    SHELL
  end
end
